# Generated by Django 2.0.4 on 2018-05-26 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu_info',
            name='cpu_gen',
        ),
        migrations.AlterField(
            model_name='cpu_info',
            name='name',
            field=models.CharField(blank=True, help_text='Intel Core i5-3470', max_length=30),
        ),
        migrations.AlterField(
            model_name='cpu_info',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cpu.Series'),
        ),
        migrations.AlterField(
            model_name='cpu_model',
            name='name',
            field=models.CharField(help_text='Core i5 or Core i3', max_length=30),
        ),
        migrations.DeleteModel(
            name='CPU_gen',
        ),
    ]
