# Generated by Django 2.0.4 on 2018-05-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0002_auto_20180526_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu_info',
            name='base_fr',
            field=models.DecimalField(decimal_places=1, help_text='Unit: GHz', max_digits=4, verbose_name='Base Frequency'),
        ),
        migrations.AlterField(
            model_name='cpu_info',
            name='cache',
            field=models.PositiveSmallIntegerField(help_text='Unit: MB', verbose_name='Cache'),
        ),
        migrations.AlterField(
            model_name='cpu_info',
            name='max_mem_bandwidth',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Max Memory bandwidth'),
        ),
        migrations.AlterField(
            model_name='cpu_info',
            name='max_memory',
            field=models.PositiveSmallIntegerField(help_text='Unit: MB'),
        ),
        migrations.AlterField(
            model_name='cpu_info',
            name='tdp',
            field=models.PositiveSmallIntegerField(help_text='Unit: W', verbose_name='Power Consumtion'),
        ),
    ]
