# Generated by Django 2.0.4 on 2018-05-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0003_auto_20180526_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu_info',
            name='proc_num',
            field=models.CharField(help_text='3470 OR 860K OR FX-3202', max_length=30, verbose_name='Processor Number'),
        ),
    ]
