# Generated by Django 2.0.4 on 2018-05-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0004_auto_20180527_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu_info',
            name='cmos',
            field=models.CharField(default=14, help_text='Unit: nm', max_length=10, verbose_name='CMOS'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpu_info',
            name='name',
            field=models.CharField(help_text='Ex: Intel Core i5-3470.', max_length=30),
        ),
        migrations.AlterField(
            model_name='cpu_info',
            name='num_of_thread',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of Threads'),
        ),
    ]
