# Generated by Django 2.0.4 on 2018-05-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0005_auto_20180527_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu_info',
            name='max_memory',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Unit: MB', null=True),
        ),
        migrations.AlterField(
            model_name='cpu_info',
            name='proc_num',
            field=models.CharField(help_text='3470 OR 860K OR FX-3202', max_length=30, null=True, verbose_name='Processor Number'),
        ),
    ]
