# Generated by Django 2.0.4 on 2018-05-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0001_initial'),
        ('cpu', '0006_auto_20180527_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu_info',
            name='memory_tech',
            field=models.ManyToManyField(to='ram.Mem_tech'),
        ),
    ]
