# Generated by Django 2.0.4 on 2018-06-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0008_auto_20180527_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu_info',
            options={'verbose_name': 'CPU Info'},
        ),
    ]
