# Generated by Django 2.0.4 on 2018-08-29 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0010_auto_20180618_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu_market',
            name='cpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpu.CPU_info'),
        ),
        migrations.AlterField(
            model_name='cpu_market',
            name='market',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.Market_info'),
        ),
    ]
