# Generated by Django 2.0.4 on 2018-09-14 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0014_auto_20180914_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='num_of_core',
            name='name',
        ),
        migrations.AlterField(
            model_name='cpu_info',
            name='cpu_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpu.CPU_brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='cpu_info',
            name='cpu_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpu.CPU_model', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='cpu_info',
            name='name',
            field=models.CharField(blank=True, help_text='Ex: Intel Core i5-3470.', max_length=100),
        ),
    ]
