# Generated by Django 2.0.4 on 2018-05-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=50)),
                ('img', models.ImageField(max_length=200, upload_to='')),
            ],
        ),
    ]
