# Generated by Django 2.0.4 on 2018-06-10 04:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory_info',
            name='data_rate',
        ),
        migrations.RemoveField(
            model_name='memory_info',
            name='name',
        ),
        migrations.AddField(
            model_name='memory_info',
            name='mem_speed',
            field=models.CharField(default='1', max_length=50, verbose_name='Memory Speed Unit(MHz | MB/s)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memory_info',
            name='model_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Item Model Number'),
        ),
        migrations.AddField(
            model_name='memory_info',
            name='num_of_pin',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number of Pin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memory_info',
            name='fr',
            field=models.PositiveIntegerField(verbose_name='Frequency Unit(MHz)'),
        ),
        migrations.AlterField(
            model_name='memory_info',
            name='moduel_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Moduel Name'),
        ),
    ]
