# Generated by Django 2.0.4 on 2018-06-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0002_auto_20180610_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory_info',
            name='capacity',
            field=models.PositiveSmallIntegerField(help_text='Unit(GB)'),
        ),
        migrations.AlterField(
            model_name='memory_info',
            name='mem_speed',
            field=models.CharField(help_text='Put the unit BY ourselve', max_length=50, verbose_name='Memory Speed Unit(MHz | MB/s)'),
        ),
    ]
