# Generated by Django 2.0.4 on 2018-06-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0004_auto_20180618_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory_info',
            name='asin',
            field=models.CharField(default='---', max_length=100, verbose_name='ASIN'),
        ),
        migrations.AddField(
            model_name='memory_info',
            name='voltage',
            field=models.CharField(blank=True, default='---', help_text='**Unit: V', max_length=100),
        ),
    ]
