# Generated by Django 2.0.4 on 2018-06-18 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0005_auto_20180618_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50, verbose_name='Moduel Name')),
                ('cycle_time', models.CharField(help_text='Unit: ns', max_length=50)),
                ('transfer_time', models.CharField(help_text='**Unit: ns', max_length=50)),
                ('command_rate', models.CharField(help_text='**Unit: MHz', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='memory_info',
            name='fr',
        ),
        migrations.RemoveField(
            model_name='memory_info',
            name='mem_speed',
        ),
        migrations.RemoveField(
            model_name='memory_info',
            name='moduel_name',
        ),
        migrations.AddField(
            model_name='memory_info',
            name='module_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ram.Module_type'),
        ),
    ]
