# Generated by Django 2.0.4 on 2018-06-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0007_auto_20180618_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory_info',
            name='asin',
        ),
    ]
