# Generated by Django 2.0.4 on 2018-06-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0008_remove_memory_info_asin'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory_market',
            name='quntity',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
