# Generated by Django 2.0.4 on 2018-06-23 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0009_memory_market_quntity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_pin', models.PositiveSmallIntegerField()),
                ('form_factor', models.CharField(help_text='eg: SO-DIMM', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='memory_info',
            name='mem_form_factor',
        ),
        migrations.RemoveField(
            model_name='memory_info',
            name='num_of_pin',
        ),
        migrations.AlterField(
            model_name='memory_info',
            name='module_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ram.Module_type'),
        ),
        migrations.AlterField(
            model_name='module_type',
            name='module_name',
            field=models.CharField(max_length=50, verbose_name='Module Name'),
        ),
        migrations.DeleteModel(
            name='Mem_form_factor',
        ),
    ]
