# Generated by Django 2.0.4 on 2018-06-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0011_mem_tech_mem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory_info',
            name='isECC',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], default='---', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='module_type',
            name='cycle_time',
            field=models.CharField(help_text='**Unit: ns', max_length=50),
        ),
    ]
