# Generated by Django 2.0.4 on 2018-06-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0012_auto_20180623_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory_info',
            name='isECC',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='---', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='memory_info',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
