# Generated by Django 2.0.4 on 2018-06-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0013_auto_20180623_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem_brand',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
