# Generated by Django 2.0.4 on 2018-06-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0014_auto_20180623_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory_info',
            name='capacity',
            field=models.DecimalField(decimal_places=3, help_text='Unit: GB', max_digits=10),
        ),
    ]
