# Generated by Django 2.0.4 on 2018-06-23 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0015_auto_20180623_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory_info',
            name='pin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ram.Pin'),
        ),
    ]
