# Generated by Django 2.0.4 on 2018-06-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0016_memory_info_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory_info',
            name='platform',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop')], max_length=10, null=True),
        ),
    ]
