# Generated by Django 2.0.4 on 2018-06-23 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0017_memory_info_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='eg: SO-DIMM', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='pin',
            name='form_factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ram.form_factor'),
        ),
    ]
