# Generated by Django 2.0.4 on 2018-06-29 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0021_auto_20180629_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module_type',
            name='command_rate',
            field=models.CharField(default='nth', help_text='**Unit: MHz', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module_type',
            name='cycle_time',
            field=models.CharField(blank=True, help_text='**Unit: ns', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='module_type',
            name='module_name',
            field=models.CharField(default='nth', max_length=50, verbose_name='Module Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module_type',
            name='transfer_time',
            field=models.CharField(blank=True, help_text='**Unit: ns', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='form_factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ram.Form_factor'),
        ),
    ]
