# Generated by Django 2.0.4 on 2018-07-01 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0023_auto_20180701_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory_info',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Unit: MB'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='form_factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ram.Form_factor'),
        ),
    ]
