# Generated by Django 2.0.4 on 2018-09-08 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0029_auto_20180908_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory_market',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Market_info'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='form_factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ram.Form_factor'),
        ),
    ]
