# Generated by Django 2.0.4 on 2019-01-06 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0034_auto_20190106_0820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory_info',
            options={'verbose_name': 'Memory Info'},
        ),
        migrations.AlterField(
            model_name='pin',
            name='form_factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ram.Form_factor'),
        ),
    ]
