# Generated by Django 2.0.4 on 2019-04-19 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0035_auto_20190106_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=400, upload_to='ram'),
        ),
        migrations.AlterField(
            model_name='memory_info',
            name='isECC',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='None', max_length=3),
        ),
        migrations.AlterField(
            model_name='memory_info',
            name='model_num',
            field=models.CharField(blank=True, default='None', max_length=100, verbose_name='Item Model Number'),
        ),
        migrations.AlterField(
            model_name='memory_info',
            name='voltage',
            field=models.CharField(blank=True, default='None', help_text='**Unit: V', max_length=100),
        ),
        migrations.AlterField(
            model_name='pin',
            name='form_factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ram.Form_factor'),
        ),
    ]
