# Generated by Django 2.0.4 on 2018-05-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0002_auto_20180526_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansion_slot',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
