# Generated by Django 2.0.4 on 2018-06-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0005_auto_20180610_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainboard_info',
            name='audio_des',
            field=models.TextField(max_length=1000, verbose_name='Audio Description'),
        ),
        migrations.AlterField(
            model_name='mainboard_info',
            name='rear_panel_des',
            field=models.TextField(max_length=1500, verbose_name='Rear Panel Description'),
        ),
    ]
