# Generated by Django 2.0.4 on 2018-06-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0006_auto_20180610_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainboard_info',
            name='interal_des',
            field=models.TextField(max_length=1500, verbose_name='Interal I\\O Connector'),
        ),
    ]
