# Generated by Django 2.0.4 on 2018-07-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0009_auto_20180617_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainboard_info',
            name='audio_des',
            field=models.TextField(default='---', max_length=1000, verbose_name='Audio Description'),
        ),
        migrations.AlterField(
            model_name='mainboard_info',
            name='cpu_des',
            field=models.TextField(default='---', max_length=300, verbose_name='CPU Description'),
        ),
        migrations.AlterField(
            model_name='mainboard_info',
            name='multi_gpu_des',
            field=models.TextField(default='---', verbose_name='Multi GPU'),
        ),
        migrations.AlterField(
            model_name='mainboard_info',
            name='name',
            field=models.CharField(help_text="Motherboard's name", max_length=100),
        ),
        migrations.AlterField(
            model_name='mainboard_info',
            name='onboard_gpu_des',
            field=models.TextField(default='---', max_length=40, verbose_name='On Board GPU'),
        ),
        migrations.AlterField(
            model_name='mainboard_info',
            name='slug',
            field=models.SlugField(blank=True, default='sss', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainboard_info',
            name='storage_des',
            field=models.TextField(default='---', max_length=500, verbose_name='Storage Description'),
        ),
    ]
