# Generated by Django 2.0.4 on 2018-07-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0010_auto_20180701_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_factor',
            old_name='desctiption',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='mainboard_info',
            name='expan_slot',
            field=models.ManyToManyField(to='mainboard.Expansion_slot', verbose_name='Expansion Slot'),
        ),
        migrations.AlterField(
            model_name='mainboard_info',
            name='name',
            field=models.CharField(help_text="Mainboard's name", max_length=100),
        ),
        migrations.AlterField(
            model_name='mainboard_info',
            name='size',
            field=models.CharField(help_text='eg : 30.5cm x 24.4cm', max_length=250),
        ),
    ]
