# Generated by Django 2.0.4 on 2018-08-29 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0011_auto_20180721_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainboard_market',
            name='mainboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainboard.Mainboard_info'),
        ),
        migrations.AlterField(
            model_name='mainboard_market',
            name='market',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.Market_info'),
        ),
    ]
