# Generated by Django 2.0.4 on 2018-09-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0013_auto_20180902_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainboard_info',
            name='onboard_gpu_des',
            field=models.TextField(default='---', verbose_name='On Board GPU'),
        ),
    ]
