# Generated by Django 2.0.4 on 2019-01-06 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0035_auto_20190106_1452'),
        ('mainboard', '0015_auto_20180908_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainboard_info',
            options={'verbose_name': 'Mainboard Info'},
        ),
        migrations.AddField(
            model_name='mainboard_info',
            name='mem_tech',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ram.Mem_tech'),
        ),
        migrations.AlterField(
            model_name='expansion_slot',
            name='pin',
            field=models.CharField(blank=True, default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='mainboard_info',
            name='audio_des',
            field=models.TextField(default='None', max_length=1000, verbose_name='Audio Description'),
        ),
        migrations.AlterField(
            model_name='mainboard_info',
            name='cpu_des',
            field=models.TextField(default='None', max_length=300, verbose_name='CPU Description'),
        ),
        migrations.AlterField(
            model_name='mainboard_info',
            name='multi_gpu_des',
            field=models.TextField(default='None', verbose_name='Multi GPU'),
        ),
        migrations.AlterField(
            model_name='mainboard_info',
            name='onboard_gpu_des',
            field=models.TextField(default='None', verbose_name='On Board GPU'),
        ),
        migrations.AlterField(
            model_name='mainboard_info',
            name='storage_des',
            field=models.TextField(default='None', max_length=500, verbose_name='Storage Description'),
        ),
    ]
