# Generated by Django 2.0.4 on 2019-04-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0016_auto_20190106_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=400, upload_to='mainboard'),
        ),
    ]
