# Generated by Django 2.0.4 on 2018-05-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainboard', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_supp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GPU_brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Graphic_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('core_clock', models.PositiveIntegerField(help_text='Unit(MHz)')),
                ('num_of_core', models.PositiveIntegerField(blank=True, null=True, verbose_name='# Number of Cores')),
                ('mem_speed', models.CharField(help_text='eg: 7 unit(Mb/s', max_length=3)),
                ('mem_cap', models.CharField(help_text='Unit(MB)', max_length=4, verbose_name='Memory Capacity')),
                ('mem_inter_width', models.CharField(help_text='eg:128 or 256,Unit(bit)', max_length=10, verbose_name='Memory Interface Width')),
                ('mem_bandwidth', models.CharField(help_text='Unit(MB/s)', max_length=5, verbose_name='Memory Bandwidth')),
                ('power', models.CharField(help_text='Unit(Watt)', max_length=5)),
                ('recom_power', models.CharField(blank=True, max_length=5, null=True, verbose_name='Recommending Power')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('api_supp', models.ManyToManyField(help_text='eg:DirectX', to='graphic.API_supp', verbose_name='API Support')),
                ('expansion_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainboard.Expansion_slot', verbose_name='Expansion Connector')),
                ('gpu', models.ForeignKey(help_text='eg:nVidia or AMD', on_delete=django.db.models.deletion.CASCADE, to='graphic.GPU', verbose_name='GPU')),
                ('gpu_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphic.GPU_brand', verbose_name='GPU Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Graphic_market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=2000)),
                ('prize', models.DecimalField(decimal_places=2, max_digits=7)),
                ('graphic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='graphic.Graphic_info')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Market_info')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('graphic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphic.Graphic_info')),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Stream Processor or CUDA or else', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vram_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='graphic_info',
            name='processor',
            field=models.ForeignKey(help_text='eg:CUDA or Stream', on_delete=django.db.models.deletion.CASCADE, to='graphic.Processor'),
        ),
        migrations.AddField(
            model_name='graphic_info',
            name='vram_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphic.Vram_type', verbose_name='Vram Type'),
        ),
    ]
