# Generated by Django 2.0.4 on 2018-05-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphic', '0002_auto_20180526_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic_info',
            name='mem_bandwidth',
            field=models.CharField(help_text='Unit: MB/s', max_length=5, verbose_name='Memory Bandwidth'),
        ),
        migrations.AlterField(
            model_name='graphic_info',
            name='mem_cap',
            field=models.CharField(help_text='Unit: MB', max_length=10, verbose_name='Memory Capacity'),
        ),
        migrations.AlterField(
            model_name='graphic_info',
            name='mem_speed',
            field=models.CharField(help_text='eg: 7000 unit: Mb/s', max_length=10),
        ),
        migrations.AlterField(
            model_name='graphic_info',
            name='power',
            field=models.CharField(help_text='Unit: W', max_length=5),
        ),
    ]
