# Generated by Django 2.0.4 on 2018-05-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphic', '0004_auto_20180526_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_supp',
            name='version',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
