# Generated by Django 2.0.4 on 2018-06-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphic', '0009_graphic_info_model_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic_info',
            name='boost_clock',
            field=models.PositiveIntegerField(blank=True, help_text='Unit(MHz)', null=True),
        ),
        migrations.AddField(
            model_name='graphic_info',
            name='dimension',
            field=models.CharField(max_length=50, null=True, verbose_name='Product Dimension'),
        ),
        migrations.AlterField(
            model_name='graphic_info',
            name='core_clock',
            field=models.PositiveIntegerField( help_text='Unit(MHz)'),
        ),
        migrations.AlterField(
            model_name='graphic_info',
            name='num_of_core',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='# Number of Cores'),
        ),
    ]
