# Generated by Django 2.0.4 on 2018-06-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphic', '0011_auto_20180617_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic_info',
            name='boost_clock',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Unit(MHz)', null=True),
        ),
    ]
