# Generated by Django 2.0.4 on 2018-06-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphic', '0012_auto_20180617_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic_info',
            name='core_clock',
            field=models.PositiveIntegerField(default=None, help_text='Unit(MHz)'),
        ),
    ]
