# Generated by Django 2.0.4 on 2018-06-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphic', '0013_auto_20180617_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic_info',
            name='boost_clock',
            field=models.PositiveIntegerField(blank=True, help_text='Unit(MHz)', null=True),
        ),
        migrations.AlterField(
            model_name='graphic_info',
            name='core_clock',
            field=models.PositiveIntegerField(help_text='Unit(MHz)'),
        ),
        migrations.AlterField(
            model_name='graphic_info',
            name='num_of_core',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='# Number of Cores'),
        ),
    ]
