# Generated by Django 2.0.4 on 2018-06-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphic', '0015_auto_20180617_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic_info',
            name='core_clock',
            field=models.PositiveIntegerField(blank=True, help_text='Unit(MHz)', null=True),
        ),
        migrations.AlterField(
            model_name='graphic_info',
            name='dimension',
            field=models.CharField(default='-', max_length=50, null=True, verbose_name='Product Dimension'),
        ),
        migrations.AlterField(
            model_name='graphic_info',
            name='mem_speed',
            field=models.CharField(help_text='eg: 7000 unit: MB/s or MHz', max_length=50),
        ),
        migrations.AlterField(
            model_name='graphic_info',
            name='model_num',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
