# Generated by Django 2.0.4 on 2018-06-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphic', '0017_auto_20180617_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic_info',
            name='boost_clock',
            field=models.CharField(blank=True, default='---', help_text='Unit :MHz', max_length=50),
        ),
        migrations.AlterField(
            model_name='graphic_info',
            name='core_clock',
            field=models.CharField(blank=True, default='---', help_text='Unit :MHz', max_length=50),
        ),
        migrations.AlterField(
            model_name='graphic_info',
            name='dimension',
            field=models.CharField(blank=True, default='---', max_length=50, verbose_name='Product Dimension'),
        ),
        migrations.AlterField(
            model_name='graphic_info',
            name='mem_bandwidth',
            field=models.CharField(blank=True, default='---', help_text='**Unit: MB/s', max_length=50, verbose_name='Memory Bandwidth'),
        ),
        migrations.AlterField(
            model_name='graphic_info',
            name='mem_cap',
            field=models.PositiveIntegerField(help_text='Unit: MB', verbose_name='Memory Capacity'),
        ),
        migrations.AlterField(
            model_name='graphic_info',
            name='mem_inter_width',
            field=models.CharField(help_text='eg:128 or 256,Unit :bit)', max_length=10, verbose_name='Memory Interface Width'),
        ),
        migrations.AlterField(
            model_name='graphic_info',
            name='mem_speed',
            field=models.CharField(blank=True, default='---', help_text='**unit: MB/s or MHz', max_length=50),
        ),
        migrations.AlterField(
            model_name='graphic_info',
            name='model_num',
            field=models.CharField(blank=True, default='---', max_length=100),
        ),
        migrations.AlterField(
            model_name='graphic_info',
            name='power',
            field=models.CharField(blank=True, default='---', help_text='Unit: W', max_length=5),
        ),
        migrations.AlterField(
            model_name='graphic_info',
            name='recom_power',
            field=models.CharField(blank=True, default='---', max_length=10, verbose_name='Recommending Power'),
        ),
        migrations.AlterField(
            model_name='graphic_info',
            name='slug',
            field=models.SlugField(blank=True, default='done', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
