# Generated by Django 2.0.4 on 2018-06-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphic', '0018_auto_20180617_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_supp',
            name='version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
