# Generated by Django 2.0.4 on 2018-06-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphic', '0020_auto_20180617_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_supp',
            name='version',
            field=models.CharField(blank=True, default=' ', max_length=10),
        ),
    ]
