# Generated by Django 2.0.4 on 2018-06-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphic', '0021_auto_20180617_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic_info',
            name='mem_bandwidth',
            field=models.CharField(blank=True, default='---', help_text='**Unit: MB/s or GB/s', max_length=50, verbose_name='Memory Bandwidth'),
        ),
    ]
