# Generated by Django 2.0.4 on 2018-07-01 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphic', '0022_auto_20180618_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic_info',
            name='processor',
            field=models.ForeignKey(blank=True, help_text='eg:CUDA or Stream', null=True, on_delete=django.db.models.deletion.CASCADE, to='graphic.Processor'),
        ),
    ]
