# Generated by Django 2.0.4 on 2018-07-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphic', '0023_auto_20180701_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic_info',
            name='mem_inter_width',
            field=models.CharField(help_text='**eg:128 or 256,Unit :bit)', max_length=10, verbose_name='Memory Interface Width'),
        ),
    ]
