# Generated by Django 2.0.4 on 2018-08-29 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphic', '0024_auto_20180701_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic_market',
            name='graphic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphic.Graphic_info'),
        ),
        migrations.AlterField(
            model_name='graphic_market',
            name='market',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.Market_info'),
        ),
    ]
