# Generated by Django 2.0.4 on 2018-09-08 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphic', '0026_auto_20180902_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic_market',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Market_info'),
        ),
    ]
