# Generated by Django 2.0.4 on 2019-01-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphic', '0027_auto_20180908_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphic_info',
            options={'verbose_name': 'CPU Info'},
        ),
    ]
